name: Copy file from one to anyother
on: push
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: sivakb/rails-template@v3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'README.md'
        destination_repo: 'sivakb/Sample'
        destination_folder: 'public'
        user_email: 'siva.kb@sprile.com'
        user_name: 'sivakb'
        commit_message: 'A custom message for the commit'